logging/base/kibana.yaml
logging/base/metadataLabelTransformer.yaml
logging/base/output.yaml
logging/base/vars.yaml
logging/overlays/minikube/output.yaml
vars/logging-config-map.env

This was also done to verify that upgrades via CLI work.

Upgrade Elasticsearch and Kibana to 7.6.0

---

common/onepanel/base/config-map.yaml
common/onepanel/base/database-secret.yaml

Changed keys.

---

common/istio/overlays/https/gateway-ingress-gateway-istio-system-patch.yaml
common/istio/overlays/https/kustomization.yaml

Resolves https://github.com/onepanelio/core/issues/92

feat(istio): add https overlay for TLS enabled istio gateway

---

gpu-plugins/base/kustomization.yaml
gpu-plugins/base/metadataLabelTransformer.yaml
gpu-plugins/overlays/amd/daemonset-amdgpu-device-plugin-daemonset-kube-system.yaml
gpu-plugins/overlays/amd/kustomization.yaml
gpu-plugins/overlays/nvidia/daemonset-nvidia-device-plugin-daemonset-kube-system.yaml
gpu-plugins/overlays/nvidia/kustomization.yaml

Resolves https://github.com/onepanelio/core/issues/98

feat(gpu): add NVIDIA and AMD device plugin daemonsets

---

common/onepanel/base/configmap-onepanel-defaultnamespace.yaml
common/onepanel/base/configmap-onepanel-onepanel.yaml
common/onepanel/base/namespace-defaultnamespace.yaml
common/onepanel/base/networkpolicy-onepanel-defaultnamespace.yaml
common/onepanel/base/role-onepanel-defaultnamespace.yaml
common/onepanel/base/rolebinding-onepanel-defaultnamespace.yaml
common/onepanel/base/secret-onepanel-default-env-defaultnamespace.yaml
common/onepanel/base/secret-onepanel-defaultnamespace.yaml
common/onepanel/base/vars.yaml
vars/onepanel-config-map.env

Parent: https://github.com/onepanelio/core/issues/114
Closes: https://github.com/onepanelio/core/issues/114

Feature/core.114 move.defaultnamespace

---

common/argo/base/cluster-role.yaml

closes https://github.com/onepanelio/core/issues/16

Adding permissions for cronworkflows to create workflows.

---

common/onepanel/base/deployment-onepanelcore-onepanel.yaml
common/onepanel/base/deployment-onepanelcoreui-onepanel.yaml
common/onepanel/base/vars.yaml

- Image Tag
- Image Pull Policy
closes https://github.com/onepanelio/core/issues/141

Added placeholders for core and coreui.

---

common/onepanel/base/configmap-onepanel-onepanel.yaml

closes https://github.com/onepanelio/core/issues/149

Adding ONEPANEL_HOST to onepanel configmap.

---

common/onepanel/base/configmap-onepanel-onepanel.yaml
common/onepanel/base/vars.yaml

closes https://github.com/onepanelio/core/issues/152

Added specified values.

---

common/onepanel/base/configmap-onepanel-onepanel.yaml
common/onepanel/base/vars.yaml
common/onepanel/overlays/cloud/service-onepanelcore-onepanel.yaml
common/onepanel/overlays/cloud/service-onepanelcoreui-onepanel.yaml

closes https://github.com/onepanelio/core/issues/160

Feat/core.160 add.url.update.host

---

common/onepanel/base/configmap-onepanel-defaultnamespace.yaml

feat: make `artifactRepository` its own key

---

common/argo/base/config-map.yaml
common/argo/base/params.env
common/argo/base/vars.yaml
vars/workflow-config-map-hidden.env

Exposes containerRuntimeExecutor parameter in params.yaml.
The user can now change this argo configuration value.
Fixes https://github.com/onepanelio/core/issues/354

feat: Exposing containerRuntimeExecutor for params.yaml.

---

common/onepanel/base/crd.yaml
common/onepanel/base/role-onepanel-defaultnamespace.yaml

Adds Workspace CRD and appropriate access to `onepanel` role in default namespace.
Fixes onepanelio/core#360

feat: Add Workspace CRD

---

common/onepanel/base/configmap-onepanel-onepanel.yaml
common/onepanel/base/vars.yaml

Extend options field in nodePool to take resource quotas.
Fixes onepanelio/core#392

fix: Add resource quotas support

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml

fix: revert.pr.76

---

common/onepanel/base/clusterrole-onepanel.yaml

fix: missing node access for onepanel

---

common/onepanel/base/vars.yaml

Removing resource examples from manifests.
- These are automatically figured out during statefulset creation
- Removing these here removes them params.yaml when `opctl init` is
executed.
Fixes onepanelio/core#634

feat: Removing resource examples from manifests.

---

common/istio/base/istio.yaml
common/istio/base/metadataLabelTransformer.yaml

Upgrades Istio to 1.7.3
There is an issue with 1.7.1 and SDS that seems to be addressed in 1.7.3

chore: Upgrade istio to 1.7.3

---

common/onepanel/base/clusterrole-onepanel-admin.yaml
common/onepanel/base/clusterrolebinding-onepanel-admin.yaml
common/onepanel/base/serviceaccount-onepanel-admin.yaml

Creates a uniform cluster admin that will not have issues with expiring tokens on GKE and EKS
Fixes onepanelio/core#648

feat: Add cluster admin

---

common/onepanel/base/clusterrole-onepanel-admin.yaml

Adds missing permission for `pods` and `pods/log`
Fixes onepanelio/core#648

fix: Add pods and pods/log permissions

---

common/onepanel/base/secret-onepanel-onepanel.yaml

Adds an hmac key to secrets for use by API
Fixes onepanelio/core#653

feat: added hmac to secrets

---

common/onepanel/base/clusterrole-onepanel.yaml

Fixes missing permission for onepanel core
Fixes onepanelio/core#653

feat: added serviceaccounts to list of resources accessible by onepanel

---

common/onepanel/base/secret-onepanel-onepanel.yaml

This reverts commit 76c7996dffd4881997f3b0fc114dadaac079630b as jwt token is reverted in API.

feat: revert addition of hmac to secrets

---

cluster-autoscaler/base/kustomization.yaml
cluster-autoscaler/overlays/eks/clusterrole.yaml
cluster-autoscaler/overlays/eks/clusterrolebinding.yaml
cluster-autoscaler/overlays/eks/deployment.yaml
cluster-autoscaler/overlays/eks/kustomization.yaml
cluster-autoscaler/overlays/eks/role.yaml
cluster-autoscaler/overlays/eks/rolebinding.yaml
cluster-autoscaler/overlays/eks/serviceaccount.yaml
cluster-autoscaler/overlays/eks/vars.yaml

feat: cluster-autoscaler for eks

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml

Update EnvoyFilter to exclude calling API from API `istio-proxy`. This is an interim fix for onepanelio/core#682
Addresses onepanelio/core#682

fix: Update EnvoyFilter to exclude calling API from API istio-proxy

---

common/onepanel/base/vars.yaml

Updates comments and defaults in generated `params.yaml` file

docs: Update comments

---

common/istio/base/deployment-ingressgateway-patch.yaml
common/istio/base/istio.yaml
common/istio/base/kustomization.yaml

feat: improve istio stability

---

common/argo/base/kustomization.yaml
common/argo/base/workflow-controller-configmap-patch-add-namespace.yaml

fix: issue where workflow-controller-configmap was not in the onepanel namespace

---

common/argo/source/base/argo-server/argo-server-deployment.yaml
common/argo/source/base/workflow-controller/workflow-controller-deployment.yaml
common/argo/source/install.yaml
common/argo/source/namespace-install.yaml
common/argo/source/quick-start-minimal.yaml
common/argo/source/quick-start-mysql.yaml
common/argo/source/quick-start-postgres.yaml

feat: update argo manifests to 2.11.8

---

common/onepanel/base/vars.yaml

docs: Add note about reserved namespaces

---

common/onepanel/base/vars.yaml

Changes the default namespace to be a variable value instead of `default`. `default` isn't recommended as it makes it harder for operations like deleting your cluster from CLI.

feat: add a placeholder for default namespace

---

common/onepanel/base/vars.yaml
gpu-plugins/overlays/gke/daemonset-nvidia-driver-installer-kube-system.yaml
gpu-plugins/overlays/gke/kustomization.yaml

Support `nvidia.com/gpu=present:NoSchedule` node taint in GKE
Fixes onepanelio/core#772

feat: Add resources.limits for better GPU support on GKE

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml

Adds a missing early-return case for envoy filter.

fix: added missing original-authority case.

---

gpu-plugins/overlays/nvidia/daemonset-nvidia-device-plugin-daemonset-kube-system.yaml

chore: Upgrade nvidia-device-plugin daemonset

---

common/onepanel/base/vars.yaml
gpu-plugins/overlays/gke/daemonset-nvidia-driver-installer-kube-system.yaml

Fixes onepanelio/core#772
Source of [Daemonset](https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/cos/daemonset-nvidia-v450.yaml)

chore: Upgrade GKE nvidia driver installer

---

common/onepanel/base/deployment-onepanelcore-onepanel.yaml

Bypasses istio proxy for outbound traffic in core

fix: Bypass istio proxy on outbound calls in core

---

common/onepanel/base/vars.yaml

docs: Update note about AKS node label

---

common/artifact-repository/overlays/abs/deployment.yaml

chore: Do not inject istio-proxy into MinIO gateway

---

common/artifact-repository/overlays/gcs/deployment.yaml
common/artifact-repository/overlays/gcs/kustomization.yaml
common/artifact-repository/overlays/gcs/secret.yaml
common/artifact-repository/overlays/gcs/service.yaml
common/artifact-repository/overlays/gcs/vars.yaml

feat: added gcs minio deployment

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml

feat: allow pre-flight requests to containers

---

vars/workflow-config-map-hidden.env

chore: remove argoExecutorImage from env file as it is no longer used

---

common/argo/base/vars.yaml

feat: default to pns for workflow engine and hide the configuration

---

common/argo/base/vars.yaml

In conjunction with https://github.com/onepanelio/cli/pull/101

chore: removed hide option as that is now handled by cli

---

common/onepanel/base/vars.yaml

docs: updated comments when setting up postgres & default username

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml
common/onepanel/overlays/expose-minio/kustomization.yaml
common/onepanel/overlays/expose-minio/service-minio-onepanel.yaml

feat: updated manifests to support exposing minio

---

cert-manager/overlays/self-signed/cluster-issuer-patch.yaml
cert-manager/overlays/self-signed/kustomization.yaml
common/artifact-repository/overlays/s3/vars.yaml
kfserving/base/config-networking-patch.yaml
kfserving/base/kfserving.yaml
kfserving/patch/serviceaccount.yaml

feat: local kfserving

---

common/onepanel/overlays/cloud/istio-envoyfilter-istioingressgatewayauth-istio-system.yaml
kfserving/base/secret.yaml

feat: onepanel-access-token header
